### ISSUE TITLE
'init()' is unavailable

### ISSUE THREAD

**Issue by filoucrx** [avdyushin/Velik#2]
In BluetoothScanner
For the class Characteristics & Service 
I have the error **'init()' is unavailable** on the init method.
'init()' has been explicitly marked unavailable here (CoreBluetooth.CBAttribute)

l26 : init(peripheral: Peripheral, service: CBService, characteristic: CBCharacteristic) {
l49 : init(peripheral: Peripheral, service: CBService) {

I use Xcode Version 12.5 (12E262)

**Comment by avdyushin** [comment]
Thanks for reporting!
